[package]
name = "squirrel-rng"
version = "0.5.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2024"
license = "MIT/Apache-2.0"
homepage = "https://github.com/archer884/squirrel-rng"
repository = "https://github.com/archer884/squirrel-rng"
keywords = ["gamedev", "random", "rng"]
categories = ["game-development"]
description = """
A fast, seedable RNG implementing `rand_core::Rng`, based on a talk by Squirrel Eiserloh.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.10.1"
getrandom = { version = "0.4", optional = true }

[features]
default = ["getrandom"]
